[package]
name = "tooltip"
version = "0.1.0"
entrypoint = "src/my-tooltip.typ"
authors = ["The Free Computing Lab <https://freecomputinglab.ohrg.org>"]
license = "MIT"
description = "A Rheo plugin for writing slides with Typst"
repository = "https://github.com/freecomputinglab/rheo-packages"

[tool.rheo.html]
js_scripts = "dist/my-tooltip.js" 
